language: python

dist: xenial

addons:
    apt:
        packages:
            - libxkbcommon-x11-0  # for PyQt 5.12

matrix:
  include:
    - python: '3.6'
      env: ORANGE="release" ORANGE_SPEC="release" RUN_PYLINT=true

    - python: '3.6'
      env: ORANGE="release"  ORANGE_SPEC="release"

    - python: '3.6'
      env: ORANGE="master"  ORANGE_SPEC="master"

cache:
    apt: true
    pip: true
    directories:
        - $TRAVIS_BUILD_DIR/pyqt

install:
    # Update pip to be able to install wheel dependencies
    - pip install -U pip wheel codecov
    - pip install pyqt5~=5.12.0 pyqtwebengine~=5.12.0
    - source $TRAVIS_BUILD_DIR/.travis/install_orange.sh
    - source $TRAVIS_BUILD_DIR/.travis/install_orange_spec.sh
    - pip install -e .
    - pip freeze

script:
    - source $TRAVIS_BUILD_DIR/.travis/stage_script.sh
