name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '20 15 15 * *'

jobs:
  normal:
    name: Usual
    uses: biolab/orange-ci-cd/.github/workflows/test-addons.yml@master
